FROM node:14.0.0

ENV CHROME_BIN=chromium
ENV NPM_CONFIG_CACHE="${WORKSPACE}/.npm"
ENV HOME="${WORKSPACE}"

WORKDIR /app

RUN apt-get update && apt-get install -y chromium

COPY package-lock.json .
COPY package.json .

RUN npm i && npm i -g @angular/cli

COPY . .