FROM node:14.20-alpine

ENV CHROME_BIN=chromium

WORKDIR /app

RUN apt-get update && apt-get install -y chromium

COPY package-lock.json .
COPY package.json .

RUN npm i && npm i -g @angular/cli

COPY . .